#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:3333}

spring:
  profiles: dev
  #Hibernate configuration
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: create-drop
  h2.console.enabled: true
  h2.console.path: /console

  zipkin:
    enabled: false

  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
        jdbc-url: jdbc:h2:mem:testdb
        platform: h2
eureka:
  client:
    enabled : false

---
spring:
  profiles: default
  #Hibernate & Oracle DB configuration
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
  datasource:

eureka:
  client:
    enabled : false

---
