--CREATE TABLE "CUSTOMER" ("ID" NUMBER(19,0), "NAME" VARCHAR2(255), "EMAIL" VARCHAR2(255));
CREATE SEQUENCE SEQ_STORE_CUSTOMER START WITH 0 INCREMENT BY 1;
INSERT INTO CUSTOMER (ID, NAME, EMAIL) VALUES (SEQ_STORE_CUSTOMER.nextval,'mkyong','111@yahoo.com');
INSERT INTO CUSTOMER (ID, NAME, EMAIL) VALUES (SEQ_STORE_CUSTOMER.nextval,'yflow','222@yahoo.com');
INSERT INTO CUSTOMER (ID, NAME, EMAIL) VALUES (SEQ_STORE_CUSTOMER.nextval,'zilap','333@yahoo.com');
